Repository Taxel/PlexTraktSync, pull requests merged in 2022-01, with the labels that each got.

#684 Add logging to README.md and Re-structure
  README.md
Labels: documentation

#688 Move GitHub installation method to CONTRIBUTING.md
  CONTRIBUTING.md
  README.md
Labels: documentation

#689 Feature: Add --local to unmatched command
  plextraktsync/commands/unmatched.py
Labels: docs needed

#703 Feature: Add on_delete listener to watcher
  plextraktsync/commands/watch.py
  plextraktsync/config.default.json
  plextraktsync/events.py
  plextraktsync/listener.py
  plextraktsync/media.py
Labels: tested, docs needed

#718 Feature: Add logic to watch to add items to collection if enabled
  plextraktsync/commands/watch.py
  plextraktsync/config.default.json
Labels: docs needed

#731 Fix: Discard pipx error output
  plextraktsync/commands/self_update.py
Labels: docs needed

#747 Fix: Disable username filter if no permission
  plextraktsync/commands/watch.py
  plextraktsync/plex_api.py
Labels: docs needed

#760 Feature: Allow inspect to take full urls as input
  plextraktsync/commands/inspect.py
Labels: docs needed
