Repository Taxel/PlexTraktSync, pull requests merged in 2022-08, with the labels that each got.

#993 Check episodes id if ordering is different between Plex and Trakt
  plextraktsync/media.py
  plextraktsync/trakt_api.py
Labels: testing-needed

#991 Plex Watchlist sync
  README.md
  plextraktsync/commands/plex_login.py
  plextraktsync/config.default.yml
  plextraktsync/config.py
  plextraktsync/media.py
  plextraktsync/plex_api.py
  plextraktsync/sync.py
  plextraktsync/trakt_api.py
  plextraktsync/walker.py
Labels: docs needed, testing-needed

#1034 Feature: Add log_console_time config option
  plextraktsync/config.default.yml
  plextraktsync/config.py
  plextraktsync/factory.py
Labels: docs needed
